'use client'
// import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider, theme } from "antd";
import "./globals.css";
import { Toaster } from "react-hot-toast";
import { ReactQueryClientProvider } from "@/lib/queryClient";

const darkTheme = {
  algorithm: theme.darkAlgorithm, // Enables the dark theme
};

// export const metadata: Metadata = {
//   title: "Employee Management System",
//   description: "Generated by Riyad Hossain",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <ReactQueryClientProvider>
          <AntdRegistry>
            <ConfigProvider theme={darkTheme}>
              <Toaster position="top-center" reverseOrder={false} />
              {children}
            </ConfigProvider>
          </AntdRegistry>
        </ReactQueryClientProvider>
      </body>
    </html>
  );
}
