import type { Metadata } from "next";
import { AntdRegistry } from "@ant-design/nextjs-registry";
import { ConfigProvider } from "antd";
import "./globals.css";

const customTheme = {
//   token: {
//     colorPrimary: "#1DA57A",
//     colorSuccess: "#52c41a",
//     colorError: "#f5222d",
//     colorWarning: "#faad14",
//     colorInfo: "#1890ff",
//   },
};

export const metadata: Metadata = {
  title: "Employee Management System",
  description: "Generated by Riyad Hossain",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <AntdRegistry>
          <ConfigProvider theme={customTheme}>{children}</ConfigProvider>
        </AntdRegistry>
      </body>
    </html>
  );
}
